// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TeddyShopWebApplication.Datos;

#nullable disable

namespace TeddyShopWebApplication.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240930111314_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CatalogoEmpleado", b =>
                {
                    b.Property<int>("Catalogo_IdCatalogo")
                        .HasColumnType("int");

                    b.Property<int>("Empleado_DniEmpleado")
                        .HasColumnType("int");

                    b.HasKey("Catalogo_IdCatalogo", "Empleado_DniEmpleado");

                    b.ToTable("CatalogoEmpleado");
                });

            modelBuilder.Entity("CatalogoProducto", b =>
                {
                    b.Property<int>("Catalogo_IdCatalogo")
                        .HasColumnType("int");

                    b.Property<int>("Producto_IdProducto")
                        .HasColumnType("int");

                    b.HasKey("Catalogo_IdCatalogo", "Producto_IdProducto");

                    b.ToTable("CatalogoProducto");
                });

            modelBuilder.Entity("Catalogo_Producto", b =>
                {
                    b.Property<int>("Catalogo_IdCatalogo")
                        .HasColumnType("int");

                    b.Property<int>("Producto_IdProducto")
                        .HasColumnType("int");

                    b.HasKey("Catalogo_IdCatalogo", "Producto_IdProducto")
                        .HasName("Catalogo_Producto_PK");

                    b.HasIndex("Producto_IdProducto");

                    b.ToTable("Catalogo_Producto", (string)null);
                });

            modelBuilder.Entity("CategoriaProducto", b =>
                {
                    b.Property<int>("Categoria_IdCategoria")
                        .HasColumnType("int");

                    b.Property<int>("Producto_IdProducto")
                        .HasColumnType("int");

                    b.HasKey("Categoria_IdCategoria", "Producto_IdProducto");

                    b.ToTable("CategoriaProducto");
                });

            modelBuilder.Entity("Categoria_Producto", b =>
                {
                    b.Property<int>("Categoria_IdCategoria")
                        .HasColumnType("int");

                    b.Property<int>("Producto_IdProducto")
                        .HasColumnType("int");

                    b.HasKey("Categoria_IdCategoria", "Producto_IdProducto")
                        .HasName("Categoria_Producto_PK");

                    b.HasIndex("Producto_IdProducto");

                    b.ToTable("Categoria_Producto", (string)null);
                });

            modelBuilder.Entity("EmpleadoPedido", b =>
                {
                    b.Property<int>("Empleado_DniEmpleado")
                        .HasColumnType("int");

                    b.Property<int>("Pedido_NumPedido")
                        .HasColumnType("int");

                    b.HasKey("Empleado_DniEmpleado", "Pedido_NumPedido");

                    b.ToTable("EmpleadoPedido");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("TeddyShopWebApplication.Models.Catalogo", b =>
                {
                    b.Property<int>("IdCatalogo")
                        .HasColumnType("int");

                    b.Property<int>("Compañia_NIT")
                        .HasColumnType("int");

                    b.Property<string>("DisponibilidadCatalogo")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("EstiloCatalogo")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("IdCatalogo")
                        .HasName("Catalogo_PK");

                    b.HasIndex("Compañia_NIT");

                    b.ToTable("Catalogo");
                });

            modelBuilder.Entity("TeddyShopWebApplication.Models.Categoria", b =>
                {
                    b.Property<int>("IdCategoria")
                        .HasColumnType("int");

                    b.Property<string>("DescripcionCategoria")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NombreCategoria")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("IdCategoria")
                        .HasName("Categoria_PK");

                    b.ToTable("Categoria");
                });

            modelBuilder.Entity("TeddyShopWebApplication.Models.Cliente", b =>
                {
                    b.Property<int>("DniCliente")
                        .HasColumnType("int");

                    b.Property<string>("ApellidoCliente")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateOnly>("FechaNaciminetoCliente")
                        .HasColumnType("date");

                    b.Property<string>("NombreCliente")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("TelefonoCliente")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("DniCliente")
                        .HasName("Cliente_PK");

                    b.ToTable("Cliente");
                });

            modelBuilder.Entity("TeddyShopWebApplication.Models.Compañia", b =>
                {
                    b.Property<int>("NIT")
                        .HasColumnType("int");

                    b.Property<string>("DIreccionEmpresa")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NombreEmpresa")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("TelefonoEmpresa")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("NIT")
                        .HasName("Compañia_PK");

                    b.ToTable("Compañia");
                });

            modelBuilder.Entity("TeddyShopWebApplication.Models.Detalle_Factura", b =>
                {
                    b.Property<int>("NumDetalle")
                        .HasColumnType("int");

                    b.Property<int>("Producto_IdProducto")
                        .HasColumnType("int");

                    b.Property<string>("CantidadDetalleFactura")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("Factura_IdFactura")
                        .HasColumnType("int");

                    b.Property<int>("Inventario_IdInventario")
                        .HasColumnType("int");

                    b.Property<decimal?>("PrecioDetalleFactura")
                        .HasColumnType("decimal(10, 3)");

                    b.HasKey("NumDetalle", "Producto_IdProducto")
                        .HasName("Detalle_Factura_PK");

                    b.HasIndex("Factura_IdFactura");

                    b.HasIndex("Inventario_IdInventario");

                    b.HasIndex("Producto_IdProducto");

                    b.ToTable("Detalle_Factura");
                });

            modelBuilder.Entity("TeddyShopWebApplication.Models.Detalle_Pedido", b =>
                {
                    b.Property<int>("NumDetalle")
                        .HasColumnType("int");

                    b.Property<string>("CantidadDetallePedido")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("Pedido_NumPedido")
                        .HasColumnType("int");

                    b.Property<decimal?>("PrecioDetallePedido")
                        .HasColumnType("decimal(10, 3)");

                    b.Property<int>("Producto_IdProducto")
                        .HasColumnType("int");

                    b.HasKey("NumDetalle")
                        .HasName("Detalle_Pedido_PK");

                    b.HasIndex("Pedido_NumPedido");

                    b.HasIndex("Producto_IdProducto");

                    b.ToTable("Detalle_Pedido");
                });

            modelBuilder.Entity("TeddyShopWebApplication.Models.Devoluciones", b =>
                {
                    b.Property<int>("IdDevolucion")
                        .HasColumnType("int");

                    b.Property<string>("DetalleDevolucion")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("IdDevolucion")
                        .HasName("Devoluciones_PK");

                    b.ToTable("Devoluciones");
                });

            modelBuilder.Entity("TeddyShopWebApplication.Models.Empleado", b =>
                {
                    b.Property<int>("DniEmpleado")
                        .HasColumnType("int");

                    b.Property<string>("CodigoEmpleado")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("Compañia_NIT")
                        .HasColumnType("int");

                    b.Property<DateOnly>("FechaNaciminetoEmpleado")
                        .HasColumnType("date");

                    b.Property<string>("NombreEmpleado")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("TelefonoEmpleado")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("UserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("DniEmpleado")
                        .HasName("Empleado_PK");

                    b.HasIndex("Compañia_NIT");

                    b.HasIndex("UserId");

                    b.ToTable("Empleado");
                });

            modelBuilder.Entity("TeddyShopWebApplication.Models.Factura", b =>
                {
                    b.Property<int>("IdFactura")
                        .HasColumnType("int");

                    b.Property<int>("Cliente_DniCliente")
                        .HasColumnType("int");

                    b.Property<DateOnly>("FechaCreacion_Factura")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("HoraCreacion_Factura")
                        .HasColumnType("time");

                    b.Property<int>("Pedido_NumPedido")
                        .HasColumnType("int");

                    b.HasKey("IdFactura")
                        .HasName("Factura_PK");

                    b.HasIndex("Cliente_DniCliente");

                    b.HasIndex("Pedido_NumPedido");

                    b.ToTable("Factura");
                });

            modelBuilder.Entity("TeddyShopWebApplication.Models.Historial_Precio", b =>
                {
                    b.Property<int>("HistorialPrecioId")
                        .HasColumnType("int");

                    b.Property<int>("Producto_IdProducto")
                        .HasColumnType("int");

                    b.Property<bool>("EstadoPrecio")
                        .HasColumnType("bit");

                    b.Property<DateOnly>("FechaFin")
                        .HasColumnType("date");

                    b.Property<DateOnly>("FechaInicio")
                        .HasColumnType("date");

                    b.Property<decimal?>("Precio")
                        .HasColumnType("decimal(10, 3)");

                    b.HasKey("HistorialPrecioId", "Producto_IdProducto")
                        .HasName("Historial_Precio_PK");

                    b.HasIndex("Producto_IdProducto");

                    b.ToTable("Historial_Precio");
                });

            modelBuilder.Entity("TeddyShopWebApplication.Models.Inventario", b =>
                {
                    b.Property<int>("IdInventario")
                        .HasColumnType("int");

                    b.Property<int>("IdDevolucion")
                        .HasColumnType("int");

                    b.Property<decimal?>("PrecioCompra")
                        .HasColumnType("decimal(10, 3)");

                    b.Property<decimal?>("PrecioVenta")
                        .HasColumnType("decimal(10, 3)");

                    b.Property<int>("Producto_IdProducto")
                        .HasColumnType("int");

                    b.Property<string>("Stock")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("StockMaximo")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("StockMinimo")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("IdInventario")
                        .HasName("Inventario_PK");

                    b.HasIndex("IdDevolucion");

                    b.ToTable("Inventario");
                });

            modelBuilder.Entity("TeddyShopWebApplication.Models.Metodo_Pago", b =>
                {
                    b.Property<int>("IdMetodoPago")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMetodoPago"));

                    b.Property<int>("Factura_IdFactura")
                        .HasColumnType("int");

                    b.Property<string>("NombreMetodoPago")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("NumPago")
                        .HasColumnType("int");

                    b.HasKey("IdMetodoPago")
                        .HasName("PK__Metodo_P__6F49A9BE6CC59531");

                    b.HasIndex("Factura_IdFactura");

                    b.ToTable("Metodo_Pago");
                });

            modelBuilder.Entity("TeddyShopWebApplication.Models.Movimiento", b =>
                {
                    b.Property<int>("IdMovimiento")
                        .HasColumnType("int");

                    b.Property<int>("CantidadIngreso")
                        .HasColumnType("int");

                    b.Property<int>("CantidadVendida")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime");

                    b.Property<int>("Inventario_IdInventario")
                        .HasColumnType("int");

                    b.HasKey("IdMovimiento")
                        .HasName("Movimiento_PK");

                    b.HasIndex("Inventario_IdInventario");

                    b.ToTable("Movimiento");
                });

            modelBuilder.Entity("TeddyShopWebApplication.Models.Pedido", b =>
                {
                    b.Property<int>("NumPedido")
                        .HasColumnType("int");

                    b.Property<string>("ApellidoAgendador")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("ApellidoComprador")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Barrio")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("Cliente_DniCliente")
                        .HasColumnType("int");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Localidad")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NombreAgendador")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NombreComprador")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NumeroAgendador")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NumeroComprador")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("TamañoOso")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("NumPedido")
                        .HasName("Pedido_PK");

                    b.HasIndex("Cliente_DniCliente");

                    b.ToTable("Pedido");
                });

            modelBuilder.Entity("TeddyShopWebApplication.Models.Producto", b =>
                {
                    b.Property<int>("IdProducto")
                        .HasColumnType("int");

                    b.Property<string>("CmCabezaColaProducto")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("CmColaPataProducto")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("DisponibilidadProducto")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("EstiloProducto")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("MaterialProducto")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("TamañoProducto")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("UserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("IdProducto")
                        .HasName("Producto_PK");

                    b.ToTable("Producto");
                });

            modelBuilder.Entity("TeddyShopWebApplication.Models.Vendedor", b =>
                {
                    b.Property<int>("DniEmpleado")
                        .HasColumnType("int");

                    b.Property<string>("CodigoVendedor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("DniEmpleado")
                        .HasName("Vendedor_PK");

                    b.HasIndex(new[] { "CodigoVendedor" }, "Vendedor_PKv1")
                        .IsUnique();

                    b.ToTable("Vendedor");
                });

            modelBuilder.Entity("Vendedor_Catalogo", b =>
                {
                    b.Property<int>("Empleado_DniEmpleado")
                        .HasColumnType("int");

                    b.Property<int>("Catalogo_IdCatalogo")
                        .HasColumnType("int");

                    b.HasKey("Empleado_DniEmpleado", "Catalogo_IdCatalogo")
                        .HasName("Vendedor_Catalogo_PK");

                    b.HasIndex("Catalogo_IdCatalogo");

                    b.ToTable("Vendedor_Catalogo", (string)null);
                });

            modelBuilder.Entity("Vendedor_Pedido", b =>
                {
                    b.Property<int>("Empleado_DniEmpleado")
                        .HasColumnType("int");

                    b.Property<int>("Pedido_NumPedido")
                        .HasColumnType("int");

                    b.HasKey("Empleado_DniEmpleado", "Pedido_NumPedido")
                        .HasName("Vendedor_Pedido_PK");

                    b.HasIndex("Pedido_NumPedido");

                    b.ToTable("Vendedor_Pedido", (string)null);
                });

            modelBuilder.Entity("Catalogo_Producto", b =>
                {
                    b.HasOne("TeddyShopWebApplication.Models.Catalogo", null)
                        .WithMany()
                        .HasForeignKey("Catalogo_IdCatalogo")
                        .IsRequired()
                        .HasConstraintName("Catalogo_Producto_Catalogo_FK");

                    b.HasOne("TeddyShopWebApplication.Models.Producto", null)
                        .WithMany()
                        .HasForeignKey("Producto_IdProducto")
                        .IsRequired()
                        .HasConstraintName("Catalogo_Producto_Producto_FK");
                });

            modelBuilder.Entity("Categoria_Producto", b =>
                {
                    b.HasOne("TeddyShopWebApplication.Models.Categoria", null)
                        .WithMany()
                        .HasForeignKey("Categoria_IdCategoria")
                        .IsRequired()
                        .HasConstraintName("Categoria_Producto_Categoria_FK");

                    b.HasOne("TeddyShopWebApplication.Models.Producto", null)
                        .WithMany()
                        .HasForeignKey("Producto_IdProducto")
                        .IsRequired()
                        .HasConstraintName("Categoria_Producto_Producto_FK");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TeddyShopWebApplication.Models.Catalogo", b =>
                {
                    b.HasOne("TeddyShopWebApplication.Models.Compañia", "Compañia_NITNavigation")
                        .WithMany("Catalogos")
                        .HasForeignKey("Compañia_NIT")
                        .IsRequired()
                        .HasConstraintName("Catalogo_Compañia_FK");

                    b.Navigation("Compañia_NITNavigation");
                });

            modelBuilder.Entity("TeddyShopWebApplication.Models.Detalle_Factura", b =>
                {
                    b.HasOne("TeddyShopWebApplication.Models.Factura", "Factura_IdFacturaNavigation")
                        .WithMany("Detalle_Facturas")
                        .HasForeignKey("Factura_IdFactura")
                        .IsRequired()
                        .HasConstraintName("Detalle_Factura_Factura_FK");

                    b.HasOne("TeddyShopWebApplication.Models.Inventario", "Inventario_IdInventarioNavigation")
                        .WithMany("Detalle_Facturas")
                        .HasForeignKey("Inventario_IdInventario")
                        .IsRequired()
                        .HasConstraintName("Detalle_Factura_Inventario_FK");

                    b.HasOne("TeddyShopWebApplication.Models.Producto", "Producto_IdProductoNavigation")
                        .WithMany("Detalle_Facturas")
                        .HasForeignKey("Producto_IdProducto")
                        .IsRequired()
                        .HasConstraintName("Detalle_Factura_Producto_FK");

                    b.Navigation("Factura_IdFacturaNavigation");

                    b.Navigation("Inventario_IdInventarioNavigation");

                    b.Navigation("Producto_IdProductoNavigation");
                });

            modelBuilder.Entity("TeddyShopWebApplication.Models.Detalle_Pedido", b =>
                {
                    b.HasOne("TeddyShopWebApplication.Models.Pedido", "Pedido_NumPedidoNavigation")
                        .WithMany("Detalle_Pedidos")
                        .HasForeignKey("Pedido_NumPedido")
                        .IsRequired()
                        .HasConstraintName("Detalle_Pedido_Pedido_FK");

                    b.HasOne("TeddyShopWebApplication.Models.Producto", "Producto_IdProductoNavigation")
                        .WithMany("Detalle_Pedidos")
                        .HasForeignKey("Producto_IdProducto")
                        .IsRequired()
                        .HasConstraintName("Detalle_Pedido_Producto_FK");

                    b.Navigation("Pedido_NumPedidoNavigation");

                    b.Navigation("Producto_IdProductoNavigation");
                });

            modelBuilder.Entity("TeddyShopWebApplication.Models.Empleado", b =>
                {
                    b.HasOne("TeddyShopWebApplication.Models.Compañia", "Compañia_NITNavigation")
                        .WithMany("Empleados")
                        .HasForeignKey("Compañia_NIT")
                        .IsRequired()
                        .HasConstraintName("Empleado_Compañia_FK");

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("Compañia_NITNavigation");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TeddyShopWebApplication.Models.Factura", b =>
                {
                    b.HasOne("TeddyShopWebApplication.Models.Cliente", "Cliente_DniClienteNavigation")
                        .WithMany("Facturas")
                        .HasForeignKey("Cliente_DniCliente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TeddyShopWebApplication.Models.Pedido", "Pedido_NumPedidoNavigation")
                        .WithMany("Facturas")
                        .HasForeignKey("Pedido_NumPedido")
                        .IsRequired()
                        .HasConstraintName("Factura_Pedido_FK");

                    b.Navigation("Cliente_DniClienteNavigation");

                    b.Navigation("Pedido_NumPedidoNavigation");
                });

            modelBuilder.Entity("TeddyShopWebApplication.Models.Historial_Precio", b =>
                {
                    b.HasOne("TeddyShopWebApplication.Models.Producto", "Producto_IdProductoNavigation")
                        .WithMany("Historial_Precios")
                        .HasForeignKey("Producto_IdProducto")
                        .IsRequired()
                        .HasConstraintName("Historial_Precio_Producto_FK");

                    b.Navigation("Producto_IdProductoNavigation");
                });

            modelBuilder.Entity("TeddyShopWebApplication.Models.Inventario", b =>
                {
                    b.HasOne("TeddyShopWebApplication.Models.Devoluciones", "IdDevolucionNavigation")
                        .WithMany("Inventarios")
                        .HasForeignKey("IdDevolucion")
                        .IsRequired()
                        .HasConstraintName("Inventario_Producto_FK");

                    b.Navigation("IdDevolucionNavigation");
                });

            modelBuilder.Entity("TeddyShopWebApplication.Models.Metodo_Pago", b =>
                {
                    b.HasOne("TeddyShopWebApplication.Models.Factura", "Factura_IdFacturaNavigation")
                        .WithMany("Metodo_Pagos")
                        .HasForeignKey("Factura_IdFactura")
                        .IsRequired()
                        .HasConstraintName("Metodo_Pago_Factura_FK");

                    b.Navigation("Factura_IdFacturaNavigation");
                });

            modelBuilder.Entity("TeddyShopWebApplication.Models.Movimiento", b =>
                {
                    b.HasOne("TeddyShopWebApplication.Models.Inventario", "Inventario_IdInventarioNavigation")
                        .WithMany("Movimientos")
                        .HasForeignKey("Inventario_IdInventario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Inventario_IdInventarioNavigation");
                });

            modelBuilder.Entity("TeddyShopWebApplication.Models.Pedido", b =>
                {
                    b.HasOne("TeddyShopWebApplication.Models.Cliente", "Cliente_DniClienteNavigation")
                        .WithMany("Pedidos")
                        .HasForeignKey("Cliente_DniCliente")
                        .IsRequired()
                        .HasConstraintName("Pedido_Cliente_FK");

                    b.Navigation("Cliente_DniClienteNavigation");
                });

            modelBuilder.Entity("TeddyShopWebApplication.Models.Vendedor", b =>
                {
                    b.HasOne("TeddyShopWebApplication.Models.Empleado", "DniEmpleadoNavigation")
                        .WithOne("Vendedor")
                        .HasForeignKey("TeddyShopWebApplication.Models.Vendedor", "DniEmpleado")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DniEmpleadoNavigation");
                });

            modelBuilder.Entity("Vendedor_Catalogo", b =>
                {
                    b.HasOne("TeddyShopWebApplication.Models.Catalogo", null)
                        .WithMany()
                        .HasForeignKey("Catalogo_IdCatalogo")
                        .IsRequired()
                        .HasConstraintName("Vendedor_Catalogo_Catalogo_FK");

                    b.HasOne("TeddyShopWebApplication.Models.Empleado", null)
                        .WithMany()
                        .HasForeignKey("Empleado_DniEmpleado")
                        .IsRequired()
                        .HasConstraintName("Vendedor_Catalogo_Empleado_FK");
                });

            modelBuilder.Entity("Vendedor_Pedido", b =>
                {
                    b.HasOne("TeddyShopWebApplication.Models.Empleado", null)
                        .WithMany()
                        .HasForeignKey("Empleado_DniEmpleado")
                        .IsRequired()
                        .HasConstraintName("Vendedor_Pedido_Empleado_FK");

                    b.HasOne("TeddyShopWebApplication.Models.Pedido", null)
                        .WithMany()
                        .HasForeignKey("Pedido_NumPedido")
                        .IsRequired()
                        .HasConstraintName("Vendedor_Pedido_Pedido_FK");
                });

            modelBuilder.Entity("TeddyShopWebApplication.Models.Cliente", b =>
                {
                    b.Navigation("Facturas");

                    b.Navigation("Pedidos");
                });

            modelBuilder.Entity("TeddyShopWebApplication.Models.Compañia", b =>
                {
                    b.Navigation("Catalogos");

                    b.Navigation("Empleados");
                });

            modelBuilder.Entity("TeddyShopWebApplication.Models.Devoluciones", b =>
                {
                    b.Navigation("Inventarios");
                });

            modelBuilder.Entity("TeddyShopWebApplication.Models.Empleado", b =>
                {
                    b.Navigation("Vendedor");
                });

            modelBuilder.Entity("TeddyShopWebApplication.Models.Factura", b =>
                {
                    b.Navigation("Detalle_Facturas");

                    b.Navigation("Metodo_Pagos");
                });

            modelBuilder.Entity("TeddyShopWebApplication.Models.Inventario", b =>
                {
                    b.Navigation("Detalle_Facturas");

                    b.Navigation("Movimientos");
                });

            modelBuilder.Entity("TeddyShopWebApplication.Models.Pedido", b =>
                {
                    b.Navigation("Detalle_Pedidos");

                    b.Navigation("Facturas");
                });

            modelBuilder.Entity("TeddyShopWebApplication.Models.Producto", b =>
                {
                    b.Navigation("Detalle_Facturas");

                    b.Navigation("Detalle_Pedidos");

                    b.Navigation("Historial_Precios");
                });
#pragma warning restore 612, 618
        }
    }
}
